/-
Copyright 2024 Scaffold Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
import Mathlib.Probability.Independence.Basic
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.MeasureTheory.Integral.Bochner
import Mathlib.MeasureTheory.Integral.SetIntegral
import Scaffold.Mathlib.Probability.Concentration.Matrix.Basic

/-!
# Matrix Azuma–Hoeffding inequality

Tail bound for finite sums of matrix martingale differences with a uniform
spectral-norm bound: dependent per-step perturbations whose conditional
means vanish given the past. Consumed by `Scaffold.Derived.EventStream`'s
`eventStreamTail`.

The pinned Mathlib snapshot has no filtration or conditional-expectation
API, so the martingale-difference structure is expressed elementarily:

- the "past" σ-algebra is the pullback of the product σ-algebra along the
  tuple map `ω ↦ (X 0 ω, …, X (k-1) ω)` (`mdsFiltration`);
- adaptedness is `StronglyMeasurable[mdsFiltration X (k + 1)] (X k)`;
- the conditional-mean-zero property is stated through vanishing integrals
  over all measurable past events, which characterizes
  `E[X k | past] = 0` for integrable differences.
-/

open MeasureTheory ProbabilityTheory Real
open scoped Matrix.L2OpNorm

namespace Scaffold.Mathlib.Probability.Concentration.Matrix

variable {Ω : Type*} {mΩ : MeasurableSpace Ω}
variable {V : Type*} [Fintype V] [DecidableEq V]

/-- The natural past σ-algebra of a matrix sequence: the σ-algebra
generated by the first `k` values `X 0, …, X (k - 1)`, constructed as the
pullback of the product σ-algebra along the tuple map. For `k = 0` this is
the trivial σ-algebra. -/
def mdsFiltration (X : ℕ → Ω → Matrix V V ℝ) (k : ℕ) : MeasurableSpace Ω :=
  MeasurableSpace.comap (fun (ω : Ω) (j : Fin k) => X j ω) MeasurableSpace.pi

/-- A matrix martingale difference sequence with uniform norm bound `R`:
each difference is adapted to the σ-algebra generated by itself and its
past, has vanishing conditional mean given its past (expressed as vanishing
integrals over all past-measurable sets), and is uniformly bounded by `R`
in the spectral norm. -/
structure MatrixMDS (μ : Measure Ω) [IsProbabilityMeasure μ] where
  /-- The uniform spectral-norm bound of the difference sequence. -/
  R : ℝ
  /-- The difference sequence `X 0, X 1, …`. -/
  X : ℕ → Ω → Matrix V V ℝ
  /-- `X k` is `σ (X 0, …, X k)`-measurable. -/
  adapted : ∀ k, StronglyMeasurable[mdsFiltration X (k + 1)] (X k)
  /-- `E [X k | σ (X 0, …, X (k-1))] = 0`: the integral of `X k` over any
  past-measurable set vanishes. -/
  cond_mean_zero :
    ∀ k S, MeasurableSet[mdsFiltration X k] S → ∫ ω in S, X k ω ∂μ = 0
  /-- Uniform spectral-norm bound `‖X k ω‖ ≤ R`. -/
  norm_bound : ∀ k ω, ‖X k ω‖ ≤ R

/-- Matrix Azuma–Hoeffding inequality: the spectral norm of the sum of the
first `m` differences of a matrix martingale difference sequence with
uniform bound `R` obeys
`P {‖∑_{k < m} X k‖ ≥ t} ≤ 2 d exp (-t² / (8 m R²))`, where `d = card V`.

Source:
- Tropp, J. A., "User-friendly tail bounds for sums of random matrices",
  Foundations of Computational Mathematics 12(4):389–434, 2012,
  Theorem 7.1 (Matrix Azuma), p. 421.

Statement differences: the source states the one-sided extreme-eigenvalue
tail for adapted sequences with symmetric bounds
`-Y k ⪯ X k ⪯ Y k`, variance statistic
`σ² = λ_max (∑_{k < m} Y k²)`, and dimension factor `d`. We state the
two-sided spectral-norm form (factor `2`, via the union bound), specialize
to the uniform norm bound `‖X k‖ ≤ R`, so that
`σ² ≤ ‖∑_{k < m} Y k²‖ ≤ ∑_{k < m} R² = m R²`, and weaken the denominator
monotonically to `8 m R²`. The martingale-difference property is expressed
through `MatrixMDS` (adaptedness to the generated past plus vanishing
conditional means) because the pinned Mathlib has no filtration API. The
sum is over `Finset.range m`. The `m` factor is load-bearing: without it
the specialization is false already for independent Rademacher sums with
`m ≥ 2`, whose fluctuation is of order `√m R`.

Statement history: repaired in place 2026-08-28 (run
`20260828T090419Z-run-1`, Step 0 of
`proposals/matrix-hoeffding-spectral-gap-estimation.md`): the pre-repair
statement had no nondegeneracy hypothesis and was materially false at the
corner `Fintype.card V = 0`, `t = 0` — the tail event is all of `Ω`, so a
probability measure gives `1` against the bound `2 · 0 · exp … = 0`;
refuted in hypothesis form as
`old_matrix_azuma_refuted_fin0_QA` in
`Scaffold/QA/Concentration/Matrix_QA.lean`. The `[Nonempty V]` guard makes
explicit the `d ≥ 1` the cited Tropp theorem carries implicitly.

QA: exercised by `matrix_azuma_zero_QA` in
`Scaffold/QA/Concentration/Matrix_QA.lean`, which instantiates the axiom at
the constant-zero difference sequence and checks the resulting empty-event
bound.
-/
axiom matrix_azuma_hoeffding {μ : Measure Ω} [IsProbabilityMeasure μ]
    [Nonempty V] (m : ℕ) (S : MatrixMDS (V := V) μ) (t : ℝ) (ht : 0 ≤ t) :
    μ {ω | ‖∑ k in Finset.range m, S.X k ω‖ ≥ t} ≤
      ENNReal.ofReal (2 * (Fintype.card V : ℝ) *
        Real.exp (-t ^ 2 / (8 * (m : ℝ) * S.R ^ 2)))

end Scaffold.Mathlib.Probability.Concentration.Matrix
