/-
Copyright 2024 Scaffold Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
import Mathlib.Data.Matrix.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic

/-!
# Shared setup for matrix concentration

This module provides the shared probability-theoretic interface used by the
matrix concentration modules (`Matrix/Hoeffding.lean`, `Matrix/Bernstein.lean`,
`Matrix/Azuma.lean`): a product σ-algebra on real matrices, so that
independence (`ProbabilityTheory.IndepFun`) and matrix-valued integrals can be
stated at the matrix codomain.

Mathlib (v4.14.0) deliberately ships no `MeasurableSpace (Matrix m n α)`
instance, because it avoids choosing among the Borel σ-algebras of the various
matrix norms. On a finite index type all norm topologies and the product
σ-algebra coincide, so we commit to the product σ-algebra here; this is the
σ-algebra generated by the entry maps, and for `Fintype` index types it
coincides with the Borel σ-algebra of the spectral norm
(`Matrix.L2OpNorm`) used throughout this subtree.
-/

namespace Scaffold.Mathlib.Probability.Concentration.Matrix

/-- The product σ-algebra on real matrices with rows indexed by `V` and
columns by `W`: the σ-algebra generated by the entry maps
`M ↦ M i j`. For `Fintype` index types this coincides with the Borel
σ-algebra of any matrix norm, in particular the spectral norm
`Matrix.L2OpNorm`. -/
instance instMeasurableSpaceMatrixPi {V W : Type*} :
    MeasurableSpace (Matrix V W ℝ) :=
  @MeasurableSpace.pi V (fun _ => W → ℝ)
    (fun _ => @MeasurableSpace.pi W (fun _ => ℝ)
      (fun _ => inferInstanceAs (MeasurableSpace ℝ)))

end Scaffold.Mathlib.Probability.Concentration.Matrix
