#!/usr/bin/env python3
"""Compiler-derived QA→shelf consumption survey (2026-09-06).

The exactness fix for the audit program's survey keys, named by three
consecutive terminal handoffs: the string-heuristic theorem-level
QA-mention survey (the last new key) produced false inert-declarations
in its closure half — caught by hand-check and recorded in
`proposals/adversarial-fences-sharp-layer-family.md` — so audit
targeting needs the answer only the elaborator can give.

Mechanics: this script generates Lean metaprogram probes that import
the public umbrella `Scaffold` plus a CO-IMPORTABLE GROUP of
`Scaffold/QA/**` modules, and computes — by memoized worklist fixpoint
over the constant graph — for every QA declaration the SHELF constants
(`Scaffold.Mathlib.*` / `Scaffold.Derived.*` defining modules) its
elaborated proof VALUE transitively depends on, and separately those
its TYPE mentions. Value-dependence and type-mention are reported
separately because they are different evidence: a value-dependence
means the QA proof consumes the shelf theorem's proof; a type-mention
means the QA statement exercises the shelf theorem's interface. The
string keys conflated these two notions, which is exactly where their
false positives and false negatives came from.

Why the closure is exact: by import direction, only constants defined
in Scaffold modules can reach Scaffold shelf constants (nothing in
Mathlib imports Scaffold), so the fixpoint universe is the Scaffold
constants alone — Mathlib intermediates provably contribute nothing
and are filtered at the edge level, not approximated.

Why groups: the QA tree carries the 24 allowlisted cross-module
duplicate names (`check_qa_name_uniqueness.py`'s residual class), and
a single file importing every QA module is exactly the "future module
that imports both" that guard documents as the collision's first
failure mode — the first run of this tool hit it on
`k2Adj._cstage1`. Modules are therefore partitioned into groups with
pairwise-disjoint exported top-level names (statically extracted; a
bisection fallback handles any extraction miss), one probe per group.

Usage:

    python3 scripts/consumption_survey.py [--out FILE] [--keep]

Report-only: nothing here is a blocking check of the verification
ladder; the census informs audit/bridge targeting and records. The
self-validation block at the end fails loudly if the tool's output
disagrees with known-true dependencies pinned in recent deliveries —
if that fires, the tool is broken, not the deliveries.
"""

import argparse
import os
import pathlib
import re
import subprocess
import sys
import collections

REPO = pathlib.Path(__file__).resolve().parent.parent
WIP = REPO / "wip"

PROBE_TEMPLATE = """import Lean
import Scaffold
{qa_imports}
open Lean Elab Command

/- Generated by scripts/consumption_survey.py — do not edit by hand.
Computes the exact QA->shelf constant-dependence edges (value vs type)
by worklist fixpoint over the Scaffold constants. Writes the TSV file
named by $CONSUMPTION_OUT. -/

run_cmd do
  let env ← getEnv
  let header := env.header.moduleNames
  let modIdxMap ← IO.mkRef (Std.HashMap.empty : Std.HashMap Name Name)
  let shelfMod ← IO.mkRef (Std.HashMap.empty : Std.HashMap Name Bool)
  let qaMod ← IO.mkRef (Std.HashMap.empty : Std.HashMap Name Bool)
  let modOf (n : Name) : Option Name :=
    match env.getModuleIdxFor? n with
    | some idx => some (header.get! idx.toNat)
    | none => none
  let isShelfM (m : Name) : Bool :=
    (`Scaffold.Mathlib).isPrefixOf m || (`Scaffold.Derived).isPrefixOf m
  let isQAmod (m : Name) : Bool := (`Scaffold.QA).isPrefixOf m
  -- the fixpoint universe: every constant defined in a Scaffold module
  let mut univ : Array Name := #[]
  for (n, _) in env.constants.toList do
    if let some m := modOf n then
      if isShelfM m || isQAmod m then
        univ := univ.push n
        modIdxMap.modify (·.insert n m)
        shelfMod.modify (·.insert n (isShelfM m))
        qaMod.modify (·.insert n (isQAmod m))
  let univSet : NameSet := univ.foldl (fun s n => s.insert n) NameSet.empty
  -- direct edges within the universe, memoized
  let directRef ← IO.mkRef (Std.HashMap.empty : Std.HashMap Name (Array Name))
  let card (t : NameSet) : Nat := t.fold (fun acc _ => acc + 1) 0
  let direct (n : Name) : CommandElabM (Array Name) := do
    if let some a := (← directRef.get).get? n then return a
    let out : Array Name :=
      match env.find? n with
      | some ci => Id.run do
        let mut o : Array Name := #[]
        for c in ci.type.getUsedConstants do
          if univSet.contains c then o := o.push c
        if let some v := ci.value? then
          for c in v.getUsedConstants do
            if univSet.contains c then o := o.push c
        return o
      | none => #[]
    directRef.modify (·.insert n out)
    return out
  -- reverse adjacency within the universe
  let revRef ← IO.mkRef (Std.HashMap.empty : Std.HashMap Name (Array Name))
  for n in univ do
    for c in ← direct n do
      revRef.modify fun r => r.insert c ((r.get? c).getD #[] |>.push n)
  -- reach sets: shelf constants reachable from a constant's type ∪ value
  let reachRef ← IO.mkRef (Std.HashMap.empty : Std.HashMap Name NameSet)
  let mut wl : Array Name := univ
  while wl.size > 0 do
    let n := wl[wl.size - 1]!
    wl := wl.pop
    let isShelf := (← shelfMod.get).get? n |>.getD false
    let mut s : NameSet := if isShelf then NameSet.empty.insert n else NameSet.empty
    for c in ← direct n do
      if let some t := (← reachRef.get).get? c then
        for x in t do s := s.insert x
    let cur := (← reachRef.get).get? n |>.getD NameSet.empty
    if card s > card cur then
      reachRef.modify fun r => r.insert n (cur.fold (·.insert ·) s)
      for p in (← revRef.get).get? n |>.getD #[] do
        wl := wl.push p
  -- emit
  let kindOf (n : Name) : String :=
    match env.find? n with
    | some (.thmInfo _) => "thm"
    | some (.defnInfo _) => "def"
    | some (.axiomInfo _) => "axiom"
    | some (.opaqueInfo _) => "opaque"
    | _ => "other"
  match ← IO.getEnv "CONSUMPTION_OUT" with
  | none => throwError "CONSUMPTION_OUT not set"
  | some outPath =>
    IO.FS.withFile outPath .write fun h => do
      for n in univ do
        if (← shelfMod.get).get? n |>.getD false then
          h.putStr s!"D\\t{{n}}\\t{{(← modIdxMap.get).get? n |>.getD Name.anonymous}}\\t{{kindOf n}}\\n"
      for n in univ do
        if (← qaMod.get).get? n |>.getD false then
          match env.find? n with
          | some ci =>
            let mut vset : NameSet := NameSet.empty
            if let some v := ci.value? then
              for c in v.getUsedConstants do
                if univSet.contains c then
                  if let some t := (← reachRef.get).get? c then
                    for x in t do vset := vset.insert x
            let mut tset : NameSet := NameSet.empty
            for c in ci.type.getUsedConstants do
              if univSet.contains c then
                if let some t := (← reachRef.get).get? c then
                  for x in t do tset := tset.insert x
            let qmod := (← modIdxMap.get).get? n |>.getD Name.anonymous
            for x in vset do h.putStr s!"V\\t{{n}}\\t{{qmod}}\\t{{x}}\\n"
            for x in tset do h.putStr s!"T\\t{{n}}\\t{{qmod}}\\t{{x}}\\n"
          | none => pure ()
    IO.println s!"consumption survey group: {{univ.size}} Scaffold constants scanned"
"""

DECL_RE = re.compile(
    r"^(?:private\s+)?(?:noncomputable\s+)?(?:protected\s+)?"
    r"(?:@\[[^\]]*\]\s*)*(theorem|lemma|def|abbrev|structure|inductive|"
    r"class|opaque|instance)\s+(?:\(\s*\)\s*)?([A-Za-z_][A-Za-z0-9_'!?]*)")
NS_RE = re.compile(r"^namespace\s+([A-Za-z0-9_.]+)")
END_RE = re.compile(r"^end\s*(?:([A-Za-z0-9_.]+)|(\S*))")


def qa_modules() -> list[pathlib.Path]:
    return sorted((REPO / "Scaffold" / "QA").rglob("*.lean"))


def exported_names(path: pathlib.Path) -> set[str]:
    """Statically extract a module's exported top-level declaration
    names (namespace-qualified). Approximate by design: misses only
    push a group into the bisection fallback, never corrupt results."""
    names: set[str] = set()
    ns: list[str] = []
    for line in path.read_text().splitlines():
        m = NS_RE.match(line)
        if m:
            ns.append(m.group(1))
            continue
        m = END_RE.match(line)
        if m and not line.startswith("end "):
            continue
        if m and m.group(1):
            if ns and ns[-1] == m.group(1):
                ns.pop()
            continue
        if line.startswith(("section", "variable", "open ", "import ",
                            "/-!", "-", "set_option")):
            continue
        dm = DECL_RE.match(line)
        if dm and dm.group(2):
            names.add(".".join(ns + [dm.group(2)]))
    return names


def partition(mods: list[pathlib.Path]) -> list[list[pathlib.Path]]:
    """Greedy partition into groups with pairwise-disjoint exported
    names (within each group)."""
    groups: list[tuple[set[str], list[pathlib.Path]]] = []
    for p in mods:
        names = exported_names(p)
        for g in groups:
            if g[0].isdisjoint(names):
                g[0].update(names)
                g[1].append(p)
                break
        else:
            groups.append((set(names), [p]))
    return [g[1] for g in groups]


def module_name(p: pathlib.Path) -> str:
    return ".".join(p.relative_to(REPO).with_suffix("").parts)


def run_group(idx: int, mods: list[pathlib.Path]) -> pathlib.Path:
    """Elaborate one probe for a group; on an import collision, bisect.
    Returns the group's edge-file path."""
    tag = f"g{idx}"
    probe = WIP / f"consumption_probe_{tag}.lean"
    out = WIP / f"consumption_edges_{tag}.tsv"
    probe.write_text(PROBE_TEMPLATE.format(
        qa_imports="\n".join(f"import {module_name(m)}" for m in mods)))
    env = dict(os.environ, CONSUMPTION_OUT=str(out))
    r = subprocess.run(["lake", "env", "lean", str(probe)],
                       cwd=REPO, capture_output=True, text=True, env=env)
    if r.returncode == 0 and out.exists():
        print(f"[survey] group {tag}: {len(mods)} modules OK "
              f"({r.stdout.strip()})")
        return out
    if len(mods) == 1:
        sys.stderr.write(r.stdout + r.stderr)
        print(f"[survey] FAIL: singleton group {mods[0]} did not "
              f"elaborate", file=sys.stderr)
        sys.exit(1)
    print(f"[survey] group {tag} collided ({len(mods)} modules); bisecting")
    half = len(mods) // 2
    a = run_group(idx, mods[:half])
    b = run_group(idx + 1000, mods[half:])
    merged = WIP / f"consumption_edges_{tag}_merged.tsv"
    merged.write_text(a.read_text() + b.read_text())
    return merged


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=pathlib.Path, default=None,
                    help="also write the census report to this file")
    ap.add_argument("--keep", action="store_true",
                    help="keep the generated probes and edge files")
    args = ap.parse_args()

    WIP.mkdir(exist_ok=True)
    for stale in WIP.glob("consumption_edges*.tsv"):
        stale.unlink()

    mods = qa_modules()
    groups = partition(mods)
    print(f"[survey] {len(mods)} QA modules partitioned into "
          f"{len(groups)} co-importable groups "
          f"(sizes {[len(g) for g in groups]})")

    edge_files = [run_group(i, g) for i, g in enumerate(groups)]

    decls: dict[str, tuple[str, str]] = {}
    value_edges: dict[str, set[str]] = {}
    type_edges: dict[str, set[str]] = {}
    # generated/derived names must not pollute the census kinds: Lean's
    # auto-generated components (`proof_N` auto-binders, `match_N`
    # equation temps, `_spec_N` simp-congruence axioms) carry thm/def/
    # axiom kinds; reclassify to "gen". Private declarations are kept
    # (real declarations, audited transitively by the fence deliveries).
    def kind_of(name: str, raw: str) -> str:
        if (re.search(r"[.](proof_|match_|spec_|eq_)[0-9]+$", name)
                or "._at." in name or name.startswith("_private.")
                or re.search(r"[.]_auxLemma([.][0-9]+)?$", name)
                or ".mk." in name
                or re.search(r"._(cstage|rarg|lambda|closed|sizeOf_)", name)
                or re.search(r"[.](casesOn|recOn|noConfusion|noConfusionType"
                             r"|brecOn|below|ibelow|binductionOn"
                             r"|imajor|majorIdx)$", name)):
            return "gen"
        return raw
    for f in edge_files:
        for line in f.read_text().splitlines():
            parts = line.split("\t")
            if parts[0] == "D":
                decls[parts[1]] = (parts[2], kind_of(parts[1], parts[3]))
            elif parts[0] == "V":
                value_edges.setdefault(parts[1], set()).add(parts[3])
            elif parts[0] == "T":
                type_edges.setdefault(parts[1], set()).add(parts[3])

    # --- self-validation against known-true dependencies ---
    KNOWN = [
        ("Scaffold.QA.SpectralGraph.prC4G_top_QA",
         "SpectralGraphTheory.googleMatrix_evals_top_eq_one"),
        ("Scaffold.QA.SpectralGraph.prCycG_second_QA",
         "SpectralGraphTheory.googleMatrix_evals_second_le"),
        ("Scaffold.QA.SpectralGraph.prCycG_bot_QA",
         "SpectralGraphTheory.evals_sum_eq_trace"),
    ]
    bad = [(q, s) for q, s in KNOWN if s not in value_edges.get(q, set())]
    if bad:
        for q, s in bad:
            print(f"[survey] VALIDATION FAIL: {q} should value-consume {s}",
                  file=sys.stderr)
        return 1
    print(f"[survey] validation: {len(KNOWN)} known-true dependencies "
          f"reproduced")

    # --- census ---
    consumed_v: set[str] = set()
    consumed_t: set[str] = set()
    for s in value_edges.values():
        consumed_v |= s
    for s in type_edges.values():
        consumed_t |= s

    lines = []

    def P(s: str = "") -> None:
        print(s)
        lines.append(s)

    thms = {n for n, (_, k) in decls.items() if k == "thm"}
    defs = {n for n, (_, k) in decls.items() if k == "def"}
    axs = {n for n, (_, k) in decls.items() if k == "axiom"}

    P("## Compiler-derived QA→shelf consumption census")
    P()
    P(f"QA declarations scanned: {len(value_edges) + len(type_edges)}"
      f" (with any shelf contact); "
      f"{sum(len(v) for v in value_edges.values())} value-edges, "
      f"{sum(len(t) for t in type_edges.values())} type-edges.")
    P()
    P(f"Shelf theorem/lemma declarations: {len(thms)}")
    P(f"  value-consumed by some QA proof : {len(thms & consumed_v)}")
    P(f"  type-mentioned only (no proof)  : {len((thms & consumed_t) - consumed_v)}")
    P(f"  never touched by QA at all      : {len(thms - consumed_v - consumed_t)}")
    P()
    P(f"Shelf defs: {len(defs)} (value-consumed {len(defs & consumed_v)}, "
      f"type-mentioned {len((defs & consumed_t) - consumed_v)}, "
      f"never {len(defs - consumed_v - consumed_t)})")
    axiom_consumers = {a: len([q for q, s in value_edges.items() if a in s])
                       for a in sorted(axs)}
    P(f"Shelf axioms: {sorted(axs)} — QA value-consumer counts: "
      f"{axiom_consumers}")
    P()

    inert = thms - consumed_v - consumed_t
    by_mod: dict[str, list[str]] = collections.defaultdict(list)
    for n in inert:
        by_mod[decls[n][0]].append(n)
    P("### Never-touched shelf theorems by module "
      f"({len(inert)} total — the exact inert census)")
    for m in sorted(by_mod):
        P(f"- {m} ({len(by_mod[m])}): " + ", ".join(sorted(by_mod[m])))
    P()

    inert_defs = defs - consumed_v - consumed_t
    dmod: dict[str, list[str]] = collections.defaultdict(list)
    for n in inert_defs:
        dmod[decls[n][0]].append(n)
    P("### Never-touched shelf defs by module "
      f"({len(inert_defs)} total)")
    for m in sorted(dmod):
        P(f"- {m} ({len(dmod[m])}): " + ", ".join(sorted(dmod[m])))
    P()

    # top-consumed shelf theorems (the load-bearing ranking)
    consumers: dict[str, set[str]] = collections.defaultdict(set)
    for q, ss in value_edges.items():
        for s in ss:
            if s in thms:
                consumers[s].add(q)
    top = sorted(consumers.items(), key=lambda kv: -len(kv[1]))[:15]
    P("### Top value-consumed shelf theorems (distinct QA consumers)")
    for s, cs in top:
        P(f"- {s}: {len(cs)}")
    P()

    if args.out:
        args.out.write_text("\n".join(lines) + "\n")
        print(f"[survey] census written to {args.out}")
    if not args.keep:
        for f in WIP.glob("consumption_edges*.tsv"):
            f.unlink()
        for f in WIP.glob("consumption_probe_g*.lean"):
            f.unlink()
    return 0


if __name__ == "__main__":
    sys.exit(main())
